boinkor-net/tsnsrv

main.go, main_test.go, nixos/default.nix, proxy.go
This lets users set custom headers (with a constant value) in case they need to talk to a weirdo service that requires headers outside the ones we set by default.
Also fixes an annoying issue I introduced very early on: I'd mistaken "upstream" for "downstream" and named some upstream-related things "downstream". Here we're fixing that naming and calling everything to do with the backend "upstream".
=> Upstream headers

main.go, nixos/default.nix
It looks like upstreams on private VLANs on my network can't be reached via the tailscale dialer. Using the non-tailscale dialer to does allow tsnsrv to reach those machines.
To this end, PR adds a `-suppressTailnetDialer=true` flag, which will use the stdlib `net.Dialer` to dial out, which _can_ reach those upstreams. It's weird, but it works!
=> New option -suppressTailnetDialer, to help access off-tailnet addresses

proxy.go
When we fail to look up a tailscale identity, previously this would dereference nil in an attempt to get at the identity fields. Let's not do that & instead return early.
=> Don't attempt to set identities from a missing identity

.github/workflows/docker-publish.yml, .github/workflows/tests.yml, .golangci.yml, main.go, proxy.go
This should leave only the linters active that I actually care about (style?) and fix the lints that golangci-lint screams about.
=> Update CI rules, improve linting

nixos/default.nix
This is the most restrictive mode, disallowing the service from ptrace-attaching (or even seeing the PIDs) of any other process on the system, even the ones running as its own user.
That's what I'd meant when setting ProtectProc to "true", but that is of course an invalid value: "Failed to parse /proc/ protection mode, ignoring: true"
=> nixos: set systemd service's ProtectProc setting to "noaccess"

.github/workflows/docker-publish.yml, Dockerfile
Maybe this will speed up the build of dependencies? Caching & splitting the many platforms' builds speeds this up enough that we can probably use it in CI without too onerous a wait time. Yay!
=> Activate the GHA cache for docker builds

go.mod
This ought to fix the CI task by using the go version that we actually need.
=> Update pinned go version in go.mod

.github/workflows/docker-publish.yml
* Adjust the condition for the `isPR` matrix key to be true, by checking the github event name: it's true if the event was pull_request or merge_group.
* Adjust all other github.event_name conditions to use the matrix.isPR context key.
This fixes #29.
=> Don't do docker pushes on merge_group builds

.github/workflows/ci_nix.yml, flake.nix, nixos/default.nix
This addresses the first part of #28: Now NixOS users have an easy way to reference a docker image that corresponds to the package we're building.
This also improves the command-line building logic by using _way_ less string interpolation. That'll be useful when we construct the docker container commandline.
=> Add a tsnsrvOciImage package and an app that streams that image

nixos/default.nix
This fixes #28, when done.
There is one really unfortunate bit about this: You can't run this rootless or as a non-root user, really (due to several problems on nixos's oci-containers side: https://github.com/NixOS/nixpkgs/issues/138423, https://github.com/NixOS/nixpkgs/issues/207050, https://github.com/containers/podman/issues/18903 and a fun bug in podman too: https://github.com/containers/podman/issues/19800).
...but otherwise, this works really well for me, at least under podman.
=> nixos: Add config for defining docker sidecars

nixos/default.nix
So we can pass arguments like "-recommendedProxyHeaders"
=> nixos: add extraArgs option to NixOS module

.github/workflows/docker-publish.yml
This should tighten some screws that #50 overly loosened: Don't build on merge group builds, and only build one push to main at a time.
=> Dedup docker builds

.github/workflows/docker-publish.yml, Dockerfile
* Set the $TARGETPLATFORM platform when requesting image bases
* Don't use the build matrix: apparently there's a race where whatever platform gets pushed first "locks" the available arches on that tag. Instead, build both on the same builder (ugh), and then push them both.
This fixes #48
=> Correct cross-compiling of docker image

.github/workflows/docker-publish.yml
It's not used, but tries to push to the main branch?! Let's drop it.
=> Drop semanticrelease from the build steps in docker-publish.yml

flake.nix
When including the flake into my nixos system and doing a rebuild I get the following error:
```
trace: warning: 'vendorSha256' is deprecated. Use 'vendorHash' instead
```
The `vendorHash` function is a drop in replacement, so with this PR the warning will be gone.
(The deprecation of `vendorSha256` can be verified by checking the [nixos 23.11 release notes](https://nixos.org/manual/nixos/stable/release-notes#sec-release-23.11) that say "The argument vendorSha256 of buildGoModule is deprecated. Use vendorHash instead. Refer to [PR #259999](https://github.com/NixOS/nixpkgs/pull/259999) for more details.")
=> Replace deprecated Nix vendorSha256 call with vendorHash

nixos/default.nix
When trying to run the nixos module service I got the following error:
```
...
error:
Failed assertions:
- tsnsrv-bla.service is ordered after 'network-online.target' but doesn't depend on it
```
And with a bit of searching I found [this nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/282795) where they try to fix similair issues.
=> Add order for nixos module systemd service

nixos/default.nix
or is only used if the left part of it does not exist. In that case we want to use the logical or ||
=> Fix missused or

nixos/default.nix
Tested this on my setup and the node appeared in my network and I could connect over it.
=> Allow to specify a default loginSeverUrl to support custom tailscale servers like headscale

main.go, nixos/default.nix
Tested this E2E with headscale and two services using the new default settings for easy templating.
=>  Add TLS listening support for custom tailscale control servers 

nixos/tests/flake-part.nix
This prevents it from attempting to connect to log.tailscale.com, which is impossible in the sandbox. Speeds up startup by a few milliseconds, but mostly reduces log spam.
=> Attempt to fix DERP connectivity in the e2e test

cli.go
This makes the unused-parameter linter happy.
=> Rename network & address to _ as they're unused

nixos/default.nix
I'd forgotten they have to be identified as "[...].service". Whoops.
=> oci containers: depend on the correct service name

nixos/default.nix, nixos/tests/cmdline/basic.nix, nixos/tests/cmdline/default.nix, nixos/tests/cmdline/with-custom-certs.nix, nixos/tests/e2e/default.nix, nixos/tests/e2e/oci.nix, nixos/tests/e2e/systemd.nix, nixos/tests/flake-part.nix, nixos/tests/helpers/cmdline_validation.nix, nixos/tests/helpers/e2e_test.nix
The nixos vm tests were getting a bit annoying to read, crammed into that flake-part.nix file. Instead, let's factor them out and in the process, add an oci-sidecar test as well.
=> Improve tests, add oci-sidecar functionality tests

nixos/default.nix
Using stop/start on system changes means that the service gets interrupted for seconds (or minutes!) at a time, which isn't really necessary in tsnsrv's case. Instead, this tells systemd to just restart the service (killing the existing process and re-executing the updated command line), which is far faster.
=> Set stopIfChanged=false on the systemd service

dev/flake-part.nix, dev/flake.lock
This version should address https://github.com/mirkolenz/flocken/issues/84, which cleans up the docker build config a bit.
=> Bump flocken to 2.5

.github/workflows/auto_update_sri_pr.yml
This is similar to what we had to do on github.com/boinkor-net/hoopsnake: The repo update token has expired, so that workflow can no longer run.
=> Fix token generation and usage for the SRI update workflow
